### PR TITLE
Horizon help link

### PR DESCRIPTION
**Pull request by shashankkatlaparthi**
The Kaizen horizon help tab by default points to RedHat documentation. The new changes will point to the new page in our website which contains FAQs and helpful links that address the usual support related questions sent to moc-kaizen-l. The aim was to bring down the general questions from our users about basic cloud issues which we deal on a frequent basis.

Please check out the link below and let me know if we need to add any new content to the page that can address the Kaizen FAQs.

https://info.massopencloud.org/blog/wiki/kaizenfaqs

### CODE REVIEW

**Comment by shashankkatlaparthi** [comment]
@kamfonik @radonm @pns005 Please review.

**Comment by kamfonik** [comment]
@shashankkatlaparthi I thought we had discussed making it a hiera variable, to make it easy to change for different deployments if needed

**Comment by kamfonik** [comment]
Also @radonm should confirm, but think all changes should go to the new repo now? 
https://github.com/CCI-MOC/MOCOSPpuppethttps://github.com/CCI-MOC/MOCOSPpuppet

**Comment by shashankkatlaparthi** [comment]
@kamfonik Puppet would address that automatically, by bad, I should have mentioned when we discussed this a while ago. Since, it is not a new parameter, and quickstack is a directory in the actual module, puppet is smart enough to pull the changes from the files/changes made in horizon module.

@radonm am I missing anything? Hiera priorities are set in the yaml config file, and it would pull the parameters from the environments, which have the horizon modules.

**Comment by radonm** [comment]
So this look good but this is the wrong repo - this needs to go into https://github.com/CCI-MOC/MOCOSPpuppet

@pns005 we should make https://github.com/CCI-MOC/liberty-puppet and https://github.com/CCI-MOC/eng1-liberty read only to avoid modification by mistake. Those are for historic purposes at the moemnt.

**Comment by shashankkatlaparthi** [comment]
@radonm @pns005 @kamfonik I think I will need be added to the repo as the contributor.

**Pull request closed without merging**
